# Generated by Django 3.1.2 on 2021-10-15 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20211015_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
