# Generated by Django 3.2.8 on 2021-10-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_newpost_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpost',
            old_name='user',
            new_name='poster',
        ),
    ]
