# Generated by Django 3.2.8 on 2021-10-20 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_rename_user_newpost_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
