# Generated by Django 3.2.8 on 2021-10-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_profileuser_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
