# Generated by Django 3.2.8 on 2021-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
