# Generated by Django 3.2.8 on 2021-10-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_auto_20211023_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
