# Generated by Django 3.2.8 on 2021-10-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_auto_20211024_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='likes',
        ),
        migrations.DeleteModel(
            name='ProfileUser',
        ),
    ]
