# Generated by Django 3.2.8 on 2021-11-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0031_alter_followers_followed'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
