# Generated by Django 3.2.8 on 2021-11-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0033_likers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='likes',
        ),
    ]
