# Generated by Django 4.0.4 on 2022-08-09 20:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0036_user_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='header_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
